In [1]:
import pandas as pd

In [2]:
import os
import shutil

In [18]:
csv=pd.read_csv("/home/user/TensorFlow/workspace/training_AS/annotations/AS_annotation_2020Sep.csv")
col_list = csv.columns.to_list()
csv

,no,MRN,Filename,BX,BY,Width,Height,Scale,label_patient,Grade,label_SIJ
0,1.0,10005192,10005192_28_0.jpg,101.604,235.946,59.833,104.990,5.3148,negative,0,negative
1,2.0,10005192,10005192_28_0.jpg,216.190,234.817,75.638,110.071,5.3148,negative,0,negative
2,3.0,10007614,10007614_34_0.jpg,98.007,205.259,52.887,92.829,5.4078,negative,0,negative
3,4.0,10007614,10007614_34_0.jpg,203.410,208.403,41.791,84.323,5.4078,negative,0,negative
4,5.0,10009480,10009480_44_0.jpg,111.217,200.041,46.294,99.738,5.3139,positive,2,positive
...,...,...,...,...,...,...,...,...,...,...,...
1887,NaN,11646202,11646202_1039_0.jpg,79.508,176.808,53.932,125.100,7.1942,positive,4,positive
1888,NaN,11661944,11661944_1048_0.jpg,156.375,43.785,43.368,92.991,7.1942,positive,4,positive
1889,NaN,11661944,11661944_1049_0.jpg,90.072,194.600,42.812,93.964,7.1942,positive,4,positive
1890,NaN,11368678,11368678_3505_0.jpg,191.125,218.786,53.932,114.397,7.1942,positive,4,positive
1891,NaN,11462772,11462772_2926_0.jpg,103.319,207.576,46.587,111.772,5.3233,positive,4,positive

In [27]:
scrdir = "/home/user/TensorFlow/workspace/training_AS/images/train/"
train_df = pd.DataFrame(columns = col_list)
for file in os.listdir(scrdir):
    row = csv.loc[csv["Filename"]== file]
    train_df = pd.concat([train_df, row], axis=0, sort=False)
train_df.to_csv(os.path.join(scrdir, "train.csv"))

In [28]:
scrdir = "/home/user/TensorFlow/workspace/training_AS/images/test/"
train_df = pd.DataFrame(columns = col_list)
for file in os.listdir(scrdir):
    row = csv.loc[csv["Filename"]== file]
    train_df = pd.concat([train_df, row], axis=0, sort=False)
train_df.to_csv(os.path.join(scrdir, "test.csv"))