In [7]:
#print(score_dict)
import pandas as pd
from sklearn.metrics import confusion_matrix
import collections
csvpath = "/home/user/TensorFlow/workspace/training_AS/images/test/test.csv"

csvfile = pd.read_csv(csvpath)
col_list = csvfile.columns.to_list()

data = list(set(csvfile.Filename.to_list()))

result_df = pd.DataFrame()

print(result_df)

Empty DataFrame
Columns: []
Index: []

In [8]:
score_lst =[0.9144595, 0.9838387, 0.961277, 0.98037463, 0.9736007, 0.9553723, 0.9574176, 0.95818555, 0.9245129, 0.6921699, 0.93881136, 0.96986467, 0.9561983, 0.9769308, 0.9742494, 0.981275, 0.94404304, 0.9671892, 0.94648176, 0.96489525, 0.9842547, 0.9820732, 0.94066364, 0.96555495, 0.9340098, 0.97256494, 0.9753347, 0.9740349, 0.9654739, 0.98226064, 0.9529662, 0.9486022, 0.9279057, 0.940678, 0.9618534, 0.9688551, 0.9620851, 0.97795606, 0.9612131, 0.9853321, 0.88697624, 0.9116414, 0.9033211, 0.96636003, 0.9854109, 0.970907, 0.9717862, 0.94377625, 0.9509869, 0.9587078, 0.9640097, 0.9669977, 0.9682828, 0.955338, 0.96289796, 0.95604736, 0.9358668, 0.72248954, 0.97208357, 0.96458656, 0.95734584, 0.9449921, 0.96345353, 0.9656745, 0.9537809, 0.8224459, 0.9680127, 0.9628996, 0.9688222, 0.022472635, 0.9772116, 0.97175, 0.9381652, 0.9780774, 0.9626399, 0.97311056, 0.9601888, 0.94004226, 0.96616656, 0.96958834, 0.9528751, 0.9634458, 0.95720375, 0.95199835, 0.910359, 0.9597629, 0.967845, 0.97792345, 0.9230829, 0.88346386, 0.9654586, 0.968568, 0.9538608, 0.9661546, 0.9243954, 0.91871053, 0.8998727, 0.88063663, 0.94652456, 0.9612558, 0.9766618, 0.9418911, 0.93923, 0.9760316, 0.82542646, 0.9565484, 0.97042733, 0.9596341, 0.93450123, 0.921805, 0.98088056, 0.97658646, 0.9582472, 0.9554098, 0.94846183, 0.029477907, 0.91959023, 0.98267245, 0.908233, 0.96444315, 0.97957027, 0.95204407, 0.9732563, 0.97365516, 0.93699676, 0.9538616, 0.96465987, 0.9729435, 0.910983, 0.8725316, 0.9358122, 0.9541222, 0.97311336, 0.939569, 0.97854567, 0.9786388, 0.9505392, 0.96785873, 0.9343897, 0.9591529, 0.9708241, 0.9629171, 0.9599739, 0.97212887, 0.9573121, 0.9094948, 0.9653211, 0.9645395, 0.9732593, 0.97344536, 0.98330104, 0.9799115, 0.9836023, 0.9668686, 0.963899, 0.9763763, 0.92320853, 0.9879963, 0.92969304, 0.97325605, 0.9645604, 0.93050474, 0.9651262, 0.96840066, 0.9622339, 0.9310377, 0.96635467, 0.975248, 0.9479649, 0.9685051, 0.8881906, 0.98384595, 0.9476819, 0.9465243, 0.96421546, 0.9554205, 0.978447, 0.944767, 0.9806326, 0.98736924, 0.9625291, 0.938436, 0.9550277, 0.95690835, 0.9665604, 0.96284413, 0.9827879, 0.97652894, 0.9164818, 0.90532887, 0.87663805, 0.97257453, 0.97267807, 0.9669735, 0.9426005, 0.9385952, 0.98214346, 0.9665033, 0.96138656, 0.9311296, 0.9742037, 0.9725892, 0.919999, 0.9777378, 0.9420148, 0.96015203, 0.9620576, 0.9633337, 0.9694456, 0.96533513, 0.94298226, 0.97899467, 0.96564597, 0.9654551, 0.93593526, 0.9268325, 0.96054316, 0.8890025, 0.95131975, 0.9823386, 0.9687357, 0.9777198, 0.9726714, 0.9684446, 0.9719963, 0.96654373, 0.6749072, 0.8993075, 0.9424339, 0.89238346, 0.8946285, 0.9610517, 0.94675416, 0.92794216, 0.9774456, 0.964649, 0.96947527, 0.9448002]

In [9]:
pred_y = [1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2]

In [10]:
result_df["classification_result"] = pred_y
result_df["score"] = score_lst
result_df

     classification_result     score
0                        1  0.914459
1                        1  0.983839
2                        1  0.961277
3                        1  0.980375
4                        1  0.973601
..                     ...       ...
233                      2  0.927942
234                      2  0.977446
235                      2  0.964649
236                      2  0.969475
237                      2  0.944800

[238 rows x 2 columns]

In [11]:
result_df.to_csv("/home/user/TensorFlow/workspace/training_AS/exported-models/my_model_200925/result2.csv")